version: '3.8'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - frontend_build:/app/result_build/
    environment:
      NODE_ENV: production
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "82:82"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      #      - ./nginx/ssl/frantsuz.crt:/etc/nginx/frantsuz.crt
      #      - ./nginx/ssl/frantsuz.key:/etc/nginx/frantsuz.key
      - frontend_build:/usr/share/nginx/html/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  frontend_build:
  static_value:
  media_value:
