# Generated by Django 3.2 on 2023-05-29 16:59

from django.db import migrations, models
import phonenumber_field.modelfields
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('PhoneNumber', phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, max_length=128, region=None, unique=True, validators=[users.validators.validate_phone_number], verbose_name='Телефон')),
                ('data', models.IntegerField(verbose_name='Возраст')),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('education', models.CharField(choices=[('secondary_edu', 'Среднее'), ('secondary_special_edu', 'Среднее специальное'), ('incomplete_higher_edu', 'Неоконченное высшее'), ('higher_edu', 'Высшее'), ('bachelor_edu', 'Бакалавр'), ('master_edu', 'Магистр'), ('candidate_science_edu', 'Кандидат наук'), ('doctor_science_edu', 'Доктор наук')], default='secondary_edu', max_length=50)),
                ('AddEducation', models.CharField(choices=[('secondary_edu', 'Среднее'), ('secondary_special_edu', 'Среднее специальное'), ('incomplete_higher_edu', 'Неоконченное высшее'), ('higher_edu', 'Высшее'), ('bachelor_edu', 'Бакалавр'), ('master_edu', 'Магистр'), ('candidate_science_edu', 'Кандидат наук'), ('doctor_science_edu', 'Доктор наук')], default='secondary_edu', max_length=50)),
                ('placeWork', models.CharField(max_length=500)),
                ('postWork', models.CharField(max_length=500, verbose_name='Должность')),
                ('DataStart', models.DateTimeField(verbose_name='Дата начала')),
                ('DataEnd', models.DateTimeField(verbose_name='Дата окончания')),
                ('About', models.CharField(max_length=500, verbose_name='О себе')),
                ('skills', models.CharField(max_length=500, verbose_name='Ключевые навыки')),
                ('startSalary', models.IntegerField(verbose_name='Зарплата от')),
                ('endSalary', models.IntegerField(verbose_name='Зарплата до')),
                ('foto', models.ImageField(upload_to='backend_media/photo', verbose_name='Изображение')),
                ('recommendation', models.FileField(blank=True, upload_to='backend_media/recommendation/', verbose_name='Файл рекомендации')),
                ('certificate', models.FileField(blank=True, upload_to='backend_media/certificate/', verbose_name='Файл сертификата')),
            ],
        ),
    ]
